Niceties 🥸
Jakobg1215/barrierts pull request #1
Opened 2022-02-07 15:10 UTC by filiphsandstrom

2022-02-09 22:07 UTC, Jakobg1215 requested changes

2022-02-09 22:07 UTC, NameIsJakob commented on src/world/PlayerManager.ts
> +                new Chat(ChatType.TEXT, `${gamelistener.player.gameProfile.name} has joined the server!`),
This should use translate instead of text. Also be the color yellow. The translate string is 'multiplayer.player.joined'.

2022-02-09 22:07 UTC, NameIsJakob commented on src/world/PlayerManager.ts
> +                gamelistener.player.gameProfile.id,
This should use an empty UUID so its not ignored by the client.

2022-02-10 21:34 UTC, Jakobg1215 approved these changes

2022-02-10 21:34 UTC, merged